# Generated by Django 4.2.9 on 2024-01-31 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('modification_time', models.DateTimeField(auto_now=True)),
                ('order_item_id', models.IntegerField(null=True)),
                ('delivered_quantity', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'delivery',
            },
        ),
    ]
